apiVersion: v1
kind: ConfigMap
metadata:
  name: java-portfolio-config
  namespace: java-portfolio
data:
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
  POSTGRES_DB: orders
  RABBITMQ_HOST: rabbitmq
  RABBITMQ_PORT: "5672"
