apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-app
  namespace: java-portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer-app
  template:
    metadata:
      labels:
        app: consumer-app
    spec:
      containers:
        - name: consumer-app
          image: java-portfolio/consumer-app:ci
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8092
          env:
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: java-portfolio-config
                  key: RABBITMQ_HOST
            - name: RABBITMQ_PORT
              valueFrom:
                configMapKeyRef:
                  name: java-portfolio-config
                  key: RABBITMQ_PORT
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: java-portfolio-secrets
                  key: RABBITMQ_DEFAULT_USER
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: java-portfolio-secrets
                  key: RABBITMQ_DEFAULT_PASS
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: consumer-app
  namespace: java-portfolio
spec:
  selector:
    app: consumer-app
  ports:
    - name: http
      port: 8092
      targetPort: 8092
