apiVersion: v1
kind: Secret
metadata:
  name: java-portfolio-secrets
  namespace: java-portfolio
type: Opaque
data:
  POSTGRES_USER: b3JkZXJzX3VzZXI=
  POSTGRES_PASSWORD: b3JkZXJzX3Bhc3M=
  RABBITMQ_DEFAULT_USER: Z3Vlc3Q=
  RABBITMQ_DEFAULT_PASS: Z3Vlc3Q=
