spring:
  application:
    name: async-notifications-consumer
  rabbitmq:
    host: localhost
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_DEFAULT_USER:guest}
    password: ${RABBITMQ_DEFAULT_PASS:guest}

server:
  port: 8092

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  config: classpath:logback-spring.xml
